"""empty message

Revision ID: 703e5748a5f5
Revises: ff6518f3e82f
Create Date: 2023-10-16 20:28:38.966807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703e5748a5f5'
down_revision = 'ff6518f3e82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
